In [2]:
conda install Advanced-Scorecard-Builder

SyntaxError: invalid syntax (<ipython-input-2-4f9c41229bf8>, line 1)

In [4]:
!pip install advanced-scorecard-builder

Collecting advanced-scorecard-builder
  Downloading https://files.pythonhosted.org/packages/67/fa/45117813d0916b74345e12e369dfb98801d3e91db9f126a24d71a33feb65/Advanced_scorecard_builder-1.1-py3-none-any.whl
Requirement already satisfied: pandas in c:\users\gosia\anaconda3\lib\site-packages (from advanced-scorecard-builder)
Collecting regressors (from advanced-scorecard-builder)
  Downloading https://files.pythonhosted.org/packages/80/5d/bacfcf2b3865305156e2507ed9a968cb6c7f326cad1d1720e60f80d02797/regressors-0.0.3.tar.gz
Requirement already satisfied: numpy>=1.9.1 in c:\users\gosia\anaconda3\lib\site-packages (from advanced-scorecard-builder)
Requirement already satisfied: python-dateutil>=2 in c:\users\gosia\anaconda3\lib\site-packages (from pandas->advanced-scorecard-builder)
Requirement already satisfied: pytz>=2011k in c:\users\gosia\anaconda3\lib\site-packages (from pandas->advanced-scorecard-builder)
Requirement already satisfied: scipy>=0.9 in c:\users\gosia\anaconda3\lib\site-packages (from regressors->advanced-scorecard-builder)
Requirement already satisfied: matplotlib in c:\users\gosia\anaconda3\lib\site-packages (from regressors->advanced-scorecard-builder)
Requirement already satisfied: scikit-learn>=0.17 in c:\users\gosia\anaconda3\lib\site-packages (from regressors->advanced-scorecard-builder)
Requirement already satisfied: statsmodels>=0.6.1 in c:\users\gosia\anaconda3\lib\site-packages (from regressors->advanced-scorecard-builder)
Requirement already satisfied: seaborn in c:\users\gosia\anaconda3\lib\site-packages (from regressors->advanced-scorecard-builder)
Requirement already satisfied: six>=1.5 in c:\users\gosia\anaconda3\lib\site-packages (from python-dateutil>=2->pandas->advanced-scorecard-builder)
Requirement already satisfied: cycler>=0.10 in c:\users\gosia\anaconda3\lib\site-packages (from matplotlib->regressors->advanced-scorecard-builder)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\gosia\anaconda3\lib\site-packages (from matplotlib->regressors->advanced-scorecard-builder)
Building wheels for collected packages: regressors
  Running setup.py bdist_wheel for regressors: started
  Running setup.py bdist_wheel for regressors: finished with status 'done'
  Stored in directory: C:\Users\gosia\AppData\Local\pip\Cache\wheels\b2\89\fc\7867f77234d0033395f7ad9814f245b337139acaa06b085aa2
Successfully built regressors
Installing collected packages: regressors, advanced-scorecard-builder
Successfully installed advanced-scorecard-builder-1.1 regressors-0.0.3

You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

In [5]:
!python -m pip install --upgrade pip

Collecting pip
  Downloading https://files.pythonhosted.org/packages/0f/74/ecd13431bcc456ed390b44c8a6e917c1820365cbebcb6a8974d1cd045ab4/pip-10.0.1-py2.py3-none-any.whl (1.3MB)
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
Successfully installed pip-10.0.1

In [6]:
from AmaFree import AdvancedScorecardBuilder as asb

In [7]:
asb()

TypeError: __init__() missing 2 required positional arguments: 'df' and 'target_name'

In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.datasets import load_iris

In [19]:
iris=load_iris()

In [20]:
df=pd.DataFrame(iris.data, columns=iris.feature_names)

In [21]:
df.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [22]:
df['target']=iris.target

In [23]:
df=df[:100]

In [24]:
test = asb(df,'target')

In [26]:
print(test.DESCR)

 Advanced ScoreCard Builder
    Parameters
    ----------
    df: DataFrame, abt dataset. With one target column

    target_name: string, target column name

    dates: string or list, optional (default=None)
     A date type columns list

    Return
    ------
    data: Pandas DataFrame, shape=[n_sample,n_features]
          data without target
    target_name: string, target column name
    target: 1d NumPy array

    _removed_features: dict with removed features from data - one value

    if dates not None
    _date_names: str, list of date column names
    _date_columns: Numpy array with date type column

    Examples
    --------

    >>> import pandas as pd
    >>> from ASB import AdvancedScorecardBuilder as asb
    >>> from sklearn.datasets import load_iris
    >>> iris = load_iris()
    >>> df = pd.DataFrame(iris.data, columns=iris.feature_names)
    >>> df['target'] = iris.target
    >>> # target with two different value
    >>> df = df[:100]
    >>> foo = asb(df,'target')
    >>> foo.fit()
    >>> foo.get_scorecard()

In [27]:
test.data

    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                 5.1               3.5                1.4               0.2
1                 4.9               3.0                1.4               0.2
2                 4.7               3.2                1.3               0.2
3                 4.6               3.1                1.5               0.2
4                 5.0               3.6                1.4               0.2
5                 5.4               3.9                1.7               0.4
6                 4.6               3.4                1.4               0.3
7                 5.0               3.4                1.5               0.2
8                 4.4               2.9                1.4               0.2
9                 4.9               3.1                1.5               0.1
10                5.4               3.7                1.5               0.2
11                4.8               3.4                1.6               0.2
12                4.8               3.0                1.4               0.1
13                4.3               3.0                1.1               0.1
14                5.8               4.0                1.2               0.2
15                5.7               4.4                1.5               0.4
16                5.4               3.9                1.3               0.4
17                5.1               3.5                1.4               0.3
18                5.7               3.8                1.7               0.3
19                5.1               3.8                1.5               0.3
20                5.4               3.4                1.7               0.2
21                5.1               3.7                1.5               0.4
22                4.6               3.6                1.0               0.2
23                5.1               3.3                1.7               0.5
24                4.8               3.4                1.9               0.2
25                5.0               3.0                1.6               0.2
26                5.0               3.4                1.6               0.4
27                5.2               3.5                1.5               0.2
28                5.2               3.4                1.4               0.2
29                4.7               3.2                1.6               0.2
..                ...               ...                ...               ...
70                5.9               3.2                4.8               1.8
71                6.1               2.8                4.0               1.3
72                6.3               2.5                4.9               1.5
73                6.1               2.8                4.7               1.2
74                6.4               2.9                4.3               1.3
75                6.6               3.0                4.4               1.4
76                6.8               2.8                4.8               1.4
77                6.7               3.0                5.0               1.7
78                6.0               2.9                4.5               1.5
79                5.7               2.6                3.5               1.0
80                5.5               2.4                3.8               1.1
81                5.5               2.4                3.7               1.0
82                5.8               2.7                3.9               1.2
83                6.0               2.7                5.1               1.6
84                5.4               3.0                4.5               1.5
85                6.0               3.4                4.5               1.6
86                6.7               3.1                4.7               1.5
87                6.3               2.3                4.4               1.3
88                5.6               3.0                4.1               1.3
89                5.5               2.5                4.0               1.3
90                5.5               2.6                4.4               1.2
91                6.1               3.0                4.6               1.4
92                5.8               2.6                4.0               1.2
93                5.0               2.3                3.3               1.0
94                5.6               2.7                4.2               1.3
95                5.7               3.0                4.2               1.2
96                5.7               2.9                4.2               1.3
97                6.2               2.9                4.3               1.3
98                5.1               2.5                3.0               1.1
99                5.7               2.8                4.1               1.3

[100 rows x 4 columns]

In [29]:
test.fit()

Matrix is singular and may not have a square root.
Matrix is singular and may not have a square root.

C:\Users\gosia\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
C:\Users\gosia\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
C:\Users\gosia\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:1738: RuntimeWarning: invalid value encountered in greater_equal
  cond2 = (x >= self.b) & cond0

In [35]:
test.get_scorecard()

                                         label           variable  score
0                     5.85 < sepal length (cm)  sepal length (cm)     65
1             5.45 < sepal length (cm) <= 5.85  sepal length (cm)     70
2  (not missing) and sepal length (cm) <= 5.45  sepal length (cm)     71
3   (not missing) and sepal width (cm) <= 2.95   sepal width (cm)     65
4              2.95 < sepal width (cm) <= 3.25   sepal width (cm)     66
5                      3.25 < sepal width (cm)   sepal width (cm)     72
6                      2.6 < petal length (cm)  petal length (cm)     65
7   (not missing) and petal length (cm) <= 2.6  petal length (cm)    103
8                       0.8 < petal width (cm)   petal width (cm)     65
9    (not missing) and petal width (cm) <= 0.8   petal width (cm)    103

In [33]:
test.model_info_

{'F1': 1.0,
 'Precision': 1.0,
 'Recall': 1.0,
 'acc': 1.0,
 'coef': {'petal length (cm)': 0.028741585767626393,
  'petal width (cm)': 0.028741585767626393,
  'sepal length (cm)': 0.011535011021492096,
  'sepal width (cm)': 0.010508036304604937},
 'features': ['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'],
 'gini': 1.0,
 'intercept': array([-0.11581391]),
 'model': 'LogisticRegressionCV',
 'p_value': {'petal length (cm)': nan,
  'petal width (cm)': nan,
  'sepal length (cm)': nan,
  'sepal width (cm)': nan}}

In [36]:
test.fit(n_category=3)
#gdy bez parametru, to podzili wtedy intuicyjnie na 4 w linii 35

Matrix is singular and may not have a square root.
Matrix is singular and may not have a square root.

C:\Users\gosia\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
C:\Users\gosia\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
C:\Users\gosia\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:1738: RuntimeWarning: invalid value encountered in greater_equal
  cond2 = (x >= self.b) & cond0

In [38]:
test.show_stats("petal width (cm)")

,score,label,Bad rate [%],Percent of population [%],n_good,n_bad,IV
0,65,0.8 < petal width (cm),100.0,42.9,1.000000e-08,3.000000e+01,22.109560
1,103,(not missing) and petal width (cm) <= 0.8,0.0,57.1,4.000000e+01,1.000000e-08,21.821878

In [59]:
dane=pd.read_csv('abt_app.csv',sep='\t',decimal='.')

In [52]:
dane=pd.DataFrame(dane)

In [53]:
dane.head()

,cid,aid,product,period,act_age,act_cc,act_loaninc,app_income,app_loan_amount,app_n_installments,...,default3,default6,default9,default12,default_cross3,default_cross6,default_cross9,default_cross12,cross_app_loan_amount,cross_app_n_installments
0,1330,css1975010100098,css,197501,45.0,0.326905,1.530456,3267.0,5000.0,24.0,...,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
1,2179,css1975010100120,css,197501,42.0,0.538908,2.903600,1722.0,5000.0,24.0,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2,146,css1975010200014,css,197501,59.0,0.543742,3.364738,1486.0,5000.0,24.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5000.0,24.0
3,479,css1975010200047,css,197501,63.0,0.587702,3.236246,1545.0,5000.0,24.0,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,4514,css1975010200151,css,197501,48.0,0.436407,1.506932,3318.0,5000.0,24.0,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
dane.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11437 entries, 0 to 11436
Columns: 219 entries, cid to cross_app_n_installments
dtypes: float64(206), int64(2), object(11)
memory usage: 19.1+ MB

In [61]:
dane=dane.drop(['aid','cid','period','cross_aid','default3','default6', 'default9','default_cross3','default_cross6','default_cross9','default_cross12'],axis=1)

In [62]:
dane.head()

,product,act_age,act_cc,act_loaninc,app_income,app_loan_amount,app_n_installments,app_number_of_children,app_spendings,app_installment,...,ags12_Min_CMaxA_Due,act12_n_arrears,act12_n_arrears_days,act12_n_good_days,decision,cross_response,cross_after_monhs,default12,cross_app_loan_amount,cross_app_n_installments
0,css,45.0,0.326905,1.530456,3267.0,5000.0,24.0,3.0,860.0,208.0,...,0.0,10.0,2.0,4.0,A,0.0,NaN,1.0,NaN,NaN
1,css,42.0,0.538908,2.903600,1722.0,5000.0,24.0,1.0,720.0,208.0,...,0.0,0.0,0.0,1.0,A,0.0,NaN,0.0,NaN,NaN
2,css,59.0,0.543742,3.364738,1486.0,5000.0,24.0,2.0,600.0,208.0,...,0.0,4.0,0.0,1.0,A,1.0,4.0,0.0,5000.0,24.0
3,css,63.0,0.587702,3.236246,1545.0,5000.0,24.0,0.0,700.0,208.0,...,0.0,3.0,0.0,4.0,A,0.0,NaN,0.0,NaN,NaN
4,css,48.0,0.436407,1.506932,3318.0,5000.0,24.0,2.0,1240.0,208.0,...,0.0,0.0,0.0,10.0,A,0.0,NaN,1.0,NaN,NaN

In [65]:
from AmaFree import AdvancedScorecardBuilder as asb

In [66]:
abt1 = asb(dane,'default12')

Exception: Your target column is not int or you have NaN values.
 Please use: df = df.dropna(subset=[target_name])
 df[target_name] = df[target_name].astype(np.int64)

In [68]:
dane = dane.dropna(subset=['default12'])

In [69]:
dane['default12'] = dane['default12'].astype(np.int64)

In [70]:
abt1 = asb(dane,'default12')

feature product removed - one value in column
feature app_loan_amount removed - one value in column
feature app_n_installments removed - one value in column
feature app_installment removed - one value in column
feature app_char_branch removed - one value in column
feature act_cus_active removed - one value in column
feature decision removed - one value in column

In [78]:
abt1.data

,act_age,act_cc,act_loaninc,app_income,app_number_of_children,app_spendings,app_char_gender,app_char_job_code,app_char_marital_status,app_char_city,...,ags12_Max_CMaxA_Due,agr12_Min_CMaxA_Due,ags12_Min_CMaxA_Due,act12_n_arrears,act12_n_arrears_days,act12_n_good_days,cross_response,cross_after_monhs,cross_app_loan_amount,cross_app_n_installments
0,45.0,0.326905,1.530456,3267.0,3.0,860.0,Female,Permanent,Maried,Big,...,3.0,0.0,0.0,10.0,2.0,4.0,0.0,NaN,NaN,NaN
1,42.0,0.538908,2.903600,1722.0,1.0,720.0,Male,Permanent,Maried,Big,...,0.0,NaN,0.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN
2,59.0,0.543742,3.364738,1486.0,2.0,600.0,Female,Retired,Maried,Big,...,1.0,0.0,0.0,4.0,0.0,1.0,1.0,4.0,5000.0,24.0
3,63.0,0.587702,3.236246,1545.0,0.0,700.0,Female,Retired,Divorced,Big,...,2.0,NaN,0.0,3.0,0.0,4.0,0.0,NaN,NaN,NaN
4,48.0,0.436407,1.506932,3318.0,2.0,1240.0,Female,Owner company,Maried,Big,...,0.0,0.0,0.0,0.0,0.0,10.0,0.0,NaN,NaN,NaN
5,49.0,0.220888,3.001200,1666.0,2.0,160.0,Male,Permanent,Maried,Medium,...,2.0,0.0,0.0,5.0,0.0,10.0,1.0,5.0,5000.0,24.0
6,51.0,0.783217,3.885004,1287.0,2.0,800.0,Female,Retired,Divorced,Large,...,0.0,0.0,0.0,0.0,0.0,11.0,0.0,NaN,NaN,NaN
7,55.0,0.622222,5.291005,945.0,0.0,380.0,Female,Contract,Divorced,Medium,...,0.0,NaN,0.0,0.0,0.0,3.0,0.0,NaN,NaN,NaN
8,60.0,0.634170,2.461841,2031.0,0.0,1080.0,Female,Retired,Maried,Large,...,0.0,0.0,0.0,0.0,0.0,8.0,0.0,NaN,NaN,NaN
9,60.0,0.620979,3.496503,1430.0,0.0,680.0,Female,Retired,Maried,Large,...,3.0,0.0,0.0,6.0,0.0,9.0,0.0,NaN,NaN,NaN
11,73.0,0.773869,12.562814,398.0,0.0,100.0,Male,Retired,Widowed,Big,...,0.0,NaN,0.0,0.0,0.0,2.0,0.0,NaN,NaN,NaN
14,59.0,0.589235,2.360718,2118.0,3.0,1040.0,Male,Permanent,Maried,Large,...,1.0,0.0,0.0,4.0,0.0,4.0,1.0,4.0,5000.0,24.0
15,50.0,0.285105,2.134016,2343.0,1.0,460.0,Female,Permanent,Maried,Medium,...,2.0,0.0,0.0,8.0,1.0,3.0,0.0,NaN,NaN,NaN
16,54.0,0.829932,8.503401,588.0,1.0,280.0,Female,Retired,Maried,Medium,...,2.0,0.0,0.0,9.0,1.0,7.0,0.0,NaN,NaN,NaN
18,59.0,0.444911,2.623295,1906.0,0.0,640.0,Male,Contract,Maried,Medium,...,1.0,NaN,0.0,3.0,0.0,1.0,0.0,NaN,NaN,NaN
19,48.0,0.304915,2.507523,1994.0,0.0,400.0,Female,Permanent,Maried,Big,...,1.0,0.0,0.0,7.0,0.0,1.0,0.0,NaN,NaN,NaN
22,62.0,0.752593,7.407407,675.0,3.0,300.0,Male,Retired,Maried,Medium,...,3.0,0.0,0.0,7.0,0.0,7.0,0.0,NaN,NaN,NaN
24,69.0,0.795181,7.530120,664.0,1.0,320.0,Female,Retired,Widowed,Medium,...,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
25,46.0,0.140639,2.283105,2190.0,1.0,100.0,Female,Permanent,Divorced,Small,...,2.0,0.0,0.0,7.0,0.0,9.0,0.0,NaN,NaN,NaN
26,71.0,0.715177,5.197505,962.0,2.0,480.0,Male,Retired,Divorced,Large,...,3.0,0.0,0.0,10.0,0.0,5.0,0.0,NaN,NaN,NaN
28,49.0,0.479070,1.453488,3440.0,2.0,1440.0,Female,Permanent,Maried,Small,...,1.0,0.0,0.0,8.0,0.0,6.0,1.0,4.0,5000.0,24.0
29,72.0,0.680851,4.432624,1128.0,0.0,560.0,Female,Retired,Widowed,Big,...,1.0,0.0,0.0,7.0,0.0,7.0,0.0,NaN,NaN,NaN
30,44.0,0.366489,1.568874,3187.0,1.0,960.0,Female,Permanent,Maried,Big,...,0.0,NaN,0.0,0.0,0.0,7.0,0.0,NaN,NaN,NaN
32,52.0,0.408464,2.299908,2174.0,0.0,680.0,Female,Permanent,Divorced,Small,...,1.0,0.0,0.0,5.0,0.0,8.0,0.0,NaN,NaN,NaN
33,66.0,0.559546,3.150599,1587.0,0.0,680.0,Female,Retired,Divorced,Big,...,2.0,0.0,0.0,10.0,2.0,5.0,0.0,NaN,NaN,NaN
34,57.0,0.448501,3.259452,1534.0,1.0,480.0,Female,Retired,Maried,Medium,...,3.0,0.0,0.0,9.0,0.0,1.0,0.0,NaN,NaN,NaN
35,66.0,0.619130,2.898551,1725.0,0.0,860.0,Male,Contract,Divorced,Medium,...,7.0,NaN,0.0,7.0,0.0,4.0,0.0,NaN,NaN,NaN
37,61.0,0.348616,2.269632,2203.0,0.0,560.0,Female,Retired,Divorced,Medium,...,1.0,0.0,0.0,3.0,0.0,7.0,1.0,4.0,5000.0,24.0
38,61.0,0.403895,2.562788,1951.0,0.0,580.0,Female,Retired,Maried,Big,...,1.0,0.0,0.0,10.0,0.0,3.0,0.0,NaN,NaN,NaN
39,51.0,0.268349,1.660578,3011.0,2.0,600.0,Female,Permanent,Maried,Big,...,0.0,0.0,0.0,0.0,0.0,11.0,0.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11405,51.0,0.271019,2.472799,2022.0,1.0,340.0,Female,Permanent,Maried,Medium,...,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
11406,71.0,0.697201,6.361323,786.0,0.0,340.0,Female,Retired,Widowed,Big,...,0.0,NaN,0.0,0.0,0.0,3.0,0.0,NaN,NaN,NaN
11407,67.0,0.407035,3.140704,1592.0,0.0,440.0,Female,Permanent,Maried,Small,...,0.0,0.0,0.0,0.0,0.0,9.0,0.0,NaN,NaN,NaN
11408,82.0,0.499425,2.876870,1738.0,1.0,660.0,Female,Retired,Divorced,Big,...,1.0,0.0,0.0,3.0,0.0,6.0,1.0,4.0,5000.0,24.0
11409,89.0,0.843615,7.173601,697.0,0.0,380.0,Female,Retired,Widowed,Big,...,1.0,0.0,0.0,2.0,0.0,7.0,0.0,NaN,NaN,NaN
11410,77.0,0.608850,4.424779,1130.0,1.0,480.0,Female,Retired,Widowed,Big,...,1.0,0.0,0.0,1.0,0.0,5.0,1.0,5.0,5000.0,24.0
11411,84.0,0.522489,3.080715,1623.0,0.0,640.0,Female,Retired,Widowed,Small,...,0.0,0.0,0.0,0.0,0.0,3.0,1.0,4.0,5000.0,24.0
11412,74.0,0.827869,5.122951,976.0,0.0,600.0,Female,Retired,Widowed,Big,...,2.0,0.0,0.0,7.0,0.0,9.0,1.0,4.0,5000.0,24.0
11413,70.0,0.974874,12.562814,398.0,0.0,180.0,Female,Retired,Maried,Medium,...,3.0,NaN,0.0,3.0,0.0,0.0,0.0,NaN,NaN,NaN
11415,68.0,0.837920,7.645260,654.0,0.0,340.0,Male,Retired,Widowed,Big,...,0.0,NaN,0.0,0.0,0.0,3.0,0.0,NaN,NaN,NaN
11416,66.0,0.820513,6.747638,741.0,0.0,400.0,Female,Retired,Maried,Big,...,1.0,0.0,0.0,1.0,0.0,9.0,0.0,NaN,NaN,NaN
11417,71.0,0.657074,5.995204,834.0,0.0,340.0,Female,Retired,Widowed,Big,...,0.0,NaN,0.0,0.0,0.0,6.0,0.0,NaN,NaN,NaN
11418,54.0,0.358812,3.158560,1583.0,0.0,360.0,Female,Permanent,Maried,Big,...,0.0,0.0,0.0,0.0,0.0,5.0,0.0,NaN,NaN,NaN
11419,55.0,0.540782,2.793296,1790.0,1.0,760.0,Female,Permanent,Maried,Large,...,2.0,0.0,0.0,8.0,1.0,5.0,0.0,NaN,NaN,NaN
11420,89.0,0.349802,2.470356,2024.0,0.0,500.0,Female,Retired,Divorced,Medium,...,2.0,1.0,1.0,12.0,0.0,5.0,1.0,4.0,5000.0,24.0
11421,66.0,0.713458,3.219575,1553.0,1.0,900.0,Female,Permanent,Widowed,Medium,...,3.0,0.0,0.0,6.0,0.0,6.0,0.0,NaN,NaN,NaN
11422,66.0,0.704403,7.861635,636.0,2.0,240.0,Female,Retired,Maried,Big,...,3.0,0.0,0.0,10.0,0.0,3.0,0.0,NaN,NaN,NaN
11423,78.0,0.742857,7.936508,630.0,1.0,260.0,Female,Retired,Widowed,Large,...,1.0,0.0,0.0,2.0,0.0,4.0,1.0,4.0,5000.0,24.0
11424,76.0,0.950820,13.661202,366.0,0.0,140.0,Female,Retired,Maried,Medium,...,2.0,0.0,0.0,10.0,1.0,6.0,1.0,4.0,5000.0,24.0
11425,52.0,0.301928,2.754821,1815.0,1.0,340.0,Male,Permanent,Maried,Big,...,1.0,0.0,0.0,4.0,0.0,4.0,0.0,NaN,NaN,NaN
11426,81.0,0.879915,5.313496,941.0,0.0,620.0,Female,Retired,Divorced,Big,...,0.0,0.0,0.0,0.0,0.0,4.0,0.0,NaN,NaN,NaN
11427,64.0,0.747613,6.821282,733.0,0.0,340.0,Male,Retired,Maried,Big,...,1.0,0.0,0.0,2.0,0.0,9.0,1.0,4.0,5000.0,24.0
11428,32.0,0.275490,3.376097,1481.0,1.0,200.0,Male,Contract,Maried,Big,...,6.0,NaN,0.0,6.0,0.0,0.0,0.0,NaN,NaN,NaN
11429,87.0,0.720801,5.561735,899.0,0.0,440.0,Male,Retired,Widowed,Big,...,0.0,0.0,0.0,0.0,0.0,11.0,0.0,NaN,NaN,NaN
11430,79.0,0.708081,2.748763,1819.0,0.0,1080.0,Female,Retired,Widowed,Medium,...,3.0,0.0,0.0,5.0,1.0,6.0,0.0,NaN,NaN,NaN
11431,65.0,0.884097,13.477089,371.0,0.0,120.0,Female,Retired,Divorced,Medium,...,5.0,NaN,0.0,6.0,1.0,0.0,0.0,NaN,NaN,NaN
11432,81.0,0.378284,2.918856,1713.0,1.0,440.0,Female,Retired,Widowed,Big,...,0.0,0.0,0.0,0.0,0.0,2.0,1.0,4.0,5000.0,24.0
11433,72.0,0.685067,3.538570,1413.0,2.0,760.0,Female,Retired,Widowed,Medium,...,2.0,0.0,0.0,7.0,1.0,1.0,1.0,4.0,5000.0,24.0
11435,90.0,0.697761,4.664179,1072.0,0.0,540.0,Male,Retired,Widowed,Big,...,1.0,0.0,0.0,6.0,0.0,5.0,1.0,4.0,5000.0,24.0
11436,71.0,0.404114,3.024803,1653.0,0.0,460.0,Female,Retired,Widowed,Small,...,2.0,0.0,0.0,3.0,0.0,3.0,1.0,4.0,5000.0,24.0

In [79]:
abt1.fit()

I removed agr9_Min_CMaxI_Due - no binns
I removed ags9_Min_CMaxI_Due - no binns
I removed agr12_Max_CMaxI_Days - no binns
I removed agr12_Min_CMaxI_Due - no binns
I removed ags12_Min_CMaxI_Due - no binns
I removed agr12_Min_CMaxC_Due - no binns
I removed ags12_Min_CMaxC_Due - no binns
I removed agr12_Min_CMaxA_Due - no binns

In [81]:
abt1.model_info_

{'F1': 0.7498176513493799,
 'Precision': 0.8006230529595015,
 'Recall': 0.7050754458161865,
 'acc': 0.7681649205812775,
 'coef': {'act_age': 0.7848358485016463,
  'act_call_cc': 1.4125987018757529,
  'act_ccss_dueutl': 0.9116296731367318,
  'act_ccss_n_statC': 0.8987505997879242,
  'agr6_Mean_CMaxI_Due': 1.1075907060890147,
  'ags12_Mean_CMaxI_Days': 1.1652914285010263,
  'app_char_job_code': 1.2692367913251346,
  'app_char_marital_status': 0.8422150157108819},
 'features': ['act_age',
  'app_char_job_code',
  'app_char_marital_status',
  'act_call_cc',
  'act_ccss_n_statC',
  'act_ccss_dueutl',
  'agr6_Mean_CMaxI_Due',
  'ags12_Mean_CMaxI_Days'],
 'gini': 0.664063271794727,
 'intercept': array([0.30587203]),
 'model': 'LogisticRegressionCV',
 'p_value': {'act_age': 0.0,
  'act_call_cc': 0.0,
  'act_ccss_dueutl': 0.0,
  'act_ccss_n_statC': 0.0,
  'agr6_Mean_CMaxI_Due': 0.0,
  'ags12_Mean_CMaxI_Days': 0.0,
  'app_char_job_code': 0.0,
  'app_char_marital_status': 0.0}}

In [84]:
abt1.html_report('Report.html')

In [85]:
#raport dostępny w katalogu DM90907